### ISSUE TITLE
شورتکات 

### ISSUE THREAD

**Issue by Hashemian01** [maleknejad/obsidian-persian-calendar#1]
<div dir=rtl>
شورتکات کار نمیکنه. نه شورتکاتی که در Core Plugin خود آبسیدین برای نوت روزانه تعریف میشه با این پلاگین کار می‌کنه و نه شورتکاتی که برای خود پلاگین تعریف میشه عمل میکنه. 
</div>

**Comment by maleknejad** [comment]
بله درسته. تست کردم کار نمیکرد.

**Comment by maleknejad** [comment]
شورتکات‌هایی که به نظرتون میتونه مفید باشه چیه؟
باز کردن روز و هفته و ماه و سال جاری رو اضافه کردم

**Comment by Hashemian01** [comment]
توی اون یکی پلاگین تقویم، امکان تعریف شورتکات برای دیروز و فردا هم وجود داره و میشه خیلی سریع بین نوت‌های امروز و فردا و دیروز سوئیچ کرد.

**Comment by maleknejad** [comment]
در نسخه جدید دستورات قرار گرفت.
