### ISSUE TITLE
عبارت معنادار برای فصل و سال

### ISSUE THREAD

**Issue by maleknejad** [maleknejad/obsidian-persian-calendar#13]
عبارت های اول و آخر فصل و اول و آخر سال هم اضافه شود

**Comment by maleknejad** [comment]
برای سال اضافه شد.

**Comment by NedaMani** [comment]
> عبارت های اول و آخر فصل و اول و آخر سال هم اضافه شود

فصل و ماه هم اضافه شده🙏
