### ISSUE TITLE
تنظیم فرمت تاریخ در مسیر

### ISSUE THREAD

**Issue by amirnano** [maleknejad/obsidian-persian-calendar#16]
ژورنال/روزانه/2024/August   
امکان این هست این کد رو جایگزاری کنیم تا تو مسیر بالا فایل ایجاد بشه؟
ژورنال/روزانه/YYYY/MMMM

**Comment by maleknejad** [comment]
سلام
ممنون از نظرتون
فعلا نمیشه. چه فایده‌ای براتون داره فولدر بندی کردن؟

**Comment by maleknejad** [comment]
ببینید منطق این افزونه اینه که همه فایل های روزنوشت در یک پوشه قرار داده بشن. هر چقدر هم زیاد بشه بار پردازشی نداره که مسئله ای بشه. و از طرفی مفید هم نیست فولدر بندی کردن ماه و سال و ... 
فایده ای نداره. ابسیدین اومده که این تیپ فولدر بندی رو بگذاریم کنار. به جاش از لینک و تگ استفاده کنید.

**Comment by NedaMani** [comment]
امکان مسیردهی داینامیک میلادی و همینطور نام‌گذاری روزنوشت به فرمت دلخواه و تنظیم هفته‌نوشت روی ابتدای سال میلادی یا شمسی در ورژن 4.8.0 پیاده‌سازی شد.
