### ISSUE TITLE
عدم نمایش روزهای تعطیل

### ISSUE THREAD

**Issue by websurfer93** [maleknejad/obsidian-persian-calendar#17]
عجب کاری با نمایش رویدادها کردی! عالی بود
فقط دو باگ برای من داشت
 وقتی که  نمایش تقویم هجری قمری را خاموش میکنم دیگه تعطیل های رسمی را نشون نمیده!
و اینکه نتونسم از کامیونیتی آپدیت را نصب کنم مجبور شدم دستی نصب کنم

**Comment by maleknejad** [comment]
سلام. اره الان دیدم که وقتی خاموش میشه تعطیل رسمی ها هم میره. 
تو اپدیت بعدی درستش میکنم.

**Comment by maleknejad** [comment]
درست شد
3.0.2
