### ISSUE TITLE
مشکل در عنوان برای ماه / فصل / سال - فرمت میلادی

### ISSUE THREAD

**Issue by pourmand1376** [maleknejad/obsidian-persian-calendar#24]
سلام. وقت شما بخیر. 

من قصد دارم از فرمت میلادی استفاده کنم چون بقیه پلاگین‌هاه هم با فرمت میلادی هستند اما افزونه شما صرفاً می‌تونه متن‌های روزانه رو با فرمت تاریخ میلادی درست کنه و متن هفتگی و ماهانه و فصلی و سالانه رو با فرمت شمسی درست می‌کنه (حتی اگر میلادی رو انتخاب کرده باشیم). 

فقط باید کمی روی UX قضیه کار بشه چون ماه / فصل / سال میلادی با شمسی فرق داره. این که چطوری این قضیه داخل تقویم نمایش داده بشه خودش ممکنه دردسر باشه.

**Comment by pourmand1376** [comment]
انتظاری که میره اینه که وقتی روی ماه یا فصل یا سال کلیک می‌کنیم، بر اساس اولین روز اون ماه یا فصل یا سال تصمیم بگیره که کدوم نوت رو باز کنه. 

مثلاً اگر روی ماه مهر کلیک کردم فایل مربوط به Sep 2024 رو باید باز کنه.

**Comment by maleknejad** [comment]
سلام وقت شما بخیر
راستش این فیچری که میگید با ذات تقویم فارسی مشکل داره. تقویم فارسی فقط و فقط در روز با میلادی یکسانه و در شماره هفته / ماه/ فصل و سال فرق میکنه. درسته میشه گفت سال 1403 معادل سال 2024 هست ولی دقیق نیست چون سال 2025 هم در این تقویم هست. از این نظر از افزونه [Periodic notes ](https://github.com/liamcain/obsidian-periodic-notes)که توسعه دهنده تقویم ابسیدین ساخته استفاده کنید به نظرم بهتره. 
ممنون از بازخوردتون

**Comment by pourmand1376** [comment]
سلام. ممنون از پاسخ‌گویی تون. 

این موردی که می‌فرمایید در صورتی که هست جامعه هدف‌تون کسانی باشند که جز پلاگین شما هیچ پلاگین دیگه ای برای مدیریت تسک‌ها نداشته باشند. 

حتماً در نظر دارید که بقیه پلاگین‌های این اکوسیستم مثل Periodic Notes و Templater با دید میلادی نوشته میشن. حتی چیزی مثل Dataview که برای گزارش گیری بسیار مفیده هم با همین پلاگینه. 

من به شخصه همه این پلاگین ها رو بصورت ترکیبی دارم و ازشون ترکیبی استفاده می‌کنم. اگر این پلاگین بخواد با اون فرمت سازگار نباشه برام قابل استفاده نیست. 

برای همین همچین فیچری رو درخواست دادم. با این حال اگر اجازه بدید یه کم بگذره ببینیم چند نفر مثل من همچین مشکلی دارند که بعد بشه راجع به راه‌حل‌ فکر کرد.

**Comment by maleknejad** [comment]
عرض بنده در مورد هفته/ماه/فصل و سال هست که تقارن دقیق شمسی ندارند
در مورد روز در نسخه دوم افزونه قابلیت نام گذاری فایل ها به میلادی رو گذاشتم که دغدغه درست شما در مورد هماهنگی با افزونه های دیگه رو رفع می‌کنه. میتونید نامگذاری روزنوشت رو میلادی کنید و مشکلی هم با دیگر افزونه ها نخواهید داشت
اگر بتونید دقیق تر بگید مشکلتون کجاست بهتر میتونم کمک کنم

**Comment by pourmand1376** [comment]
بسیار خب بگذارید دقیق‌تر توضیح بدم. برای روز مشکلی نیست چون تقارن دقیق داره. 

برای ماه تقارن نداره مثلاً ماه مهر معادل سپتامبر و اکتبر هست. نرم‌افزار Periodic Notes و Templater برای من سپتامبر رو ساخته و با اون سیستم هم همه نوت‌هام رو جلو بردم. حالا اگر روی ماه در نرم‌افزار شما کلیک کنم ماه مهر برام ساخته میشه. در حالی که من انتظار دارم به نوت سپتامبر مراجعه کنه. 

فصل‌ها تقارن تقریبی دارند ولی باز هم انتظار دارم وقتی روی زمستان کلیک می‌کنم، به همون چیزی که Templater ساخته هدایت بشم. یعنی مثلا 2024-Q1. 

ولی واقعاً هیچ ایده‌ای ندارم چند نفر مثل من همچین چیز نسبتاً عجیبی رو انتظار دارند که موقعی که روی ماه / فصل / سال شمسی کلیک می‌کنند به ماه / فصل / سال تقریبی در میلادی هدایت بشن.

**Comment by maleknejad** [comment]
حرف شما رو درک میکنم ولی حس میکنم پیچیدگی رو بالا می‌بره. با alias نمی‌تونید هندل کنید؟ مثلا فرض کنید ماه‌نوشت شمسی باشه داخل alias ماه معادل میلادیش رو بنویسید
داخل فایل ماه‌نوشت یا فصل‌نوشتتون فانکشن خاصی دارید که به اسم ربط داره؟

**Comment by pourmand1376** [comment]
بله. همه این نوت‌ها به هم لینک دارند. 

ولی ایده‌ای که دادید ایده خوبی هست. میتونم هر نوتی که از سمت شما ساخته میشه رو اتوماتیک به نوت‌های معادل میلادی اش متصل کنم و قضیه حل میشه. 

نیازی به تغییر از سمت شما هم نیست.

**Comment by maleknejad** [comment]
خوشحالم که تونستم کمک‌تون کنم. باز هم نکته‌ای بود بگید در خدمتتون هستم.
