### ISSUE TITLE
ارور هنگام ایجاد روزنوشت

### ISSUE THREAD

**Issue by Daniwx5** [maleknejad/obsidian-persian-calendar#4]
وقت بخیر. ممنونم بابت پلاگین زیباتون.

من برای تعریف مسیر فایل‌ها راه‌های زیر رو امتحان کردم اما بعد از تلاش برای ایجاد نوت با خطای 

`error opening/creating daily note`
مواجه شدم.

اینا شیوه هاییه که برای تعریف مسیر امتحان کردم:

```
C:\Users\[username]\OneDrive\Obsidian\[my vault's name]\[my folder's name]
OneDrive\Obsidian\[my vault's name]\[my folder's name]
Obsidian\[my vault's name]\[my folder's name]
[my vault's name]\[my folder's name]
```
ممنون میشم اگه راهنماییم کنید.

**Comment by maleknejad** [comment]
سلام دوست عزیز
ممنون
مسیر رو از جایی که به عنوان vault تعریف کردید شروع کنید نه جایی که فایل در سیستم هست
کلا سیستم تعریف مسیر در ابسیدین به این  نحو هست
اینطوری:

[my folder's name]/...

**Comment by Daniwx5** [comment]
درود بر شما.
ممنونم از شکیبایی و پاسخگویی‌تون، مشکلم برطرف شد.
 زنده باشید.
