### ISSUE TITLE
اضافه کردن قابلیت پوشه بندی نوت ها به صورت خودکار

### ISSUE THREAD

**Issue by Aligh22** [maleknejad/obsidian-persian-calendar#8]
با سلام و خسته نباشید
بعد از چند ماه یا چند سال فایل نوت ها در یک پوشه DailyNote خیلی زیاد میشه
اگر بتونین کاری کنین نوت ها به صورت خودکار بر اساس سال/فصل/ماه/هفته ذخیره بشن خوب میشه (یا قابلیتش به صورت اختیاری قرار بگیره در تنظیمات)
@maleknejad

**Comment by maleknejad** [comment]
ابسیدین مشکلی با تعداد نوت بالا نداره. من بیش از 5000 نوت در والتم دارم و در عملکرد نرم افزار اختلالی ایجاد نشده. این استرس تست رو تا پنجاه هزار فایل هم گرفتم و مشکلی نداشته. 
البته که ایده‌تون از منظر اینکه در فایل باشه شدنی هست. اگر فایل رو با این فرمت رفرنس بدید کل فایل یا هدینگ مشخصی رو میتونه نشون بده: ![[]]
موفق باشید
