### ISSUE TITLE
لینک اشتباه در توضیحات

### ISSUE THREAD

**Issue by Hashemian01** [maleknejad/obsidian-persian-calendar#9]
![image](https://github.com/maleknejad/obsidian-persian-calendar/assets/48093461/a1b3358c-9477-4eb0-b908-45f23b6000dd)

یه چیز خیلی جزئی هست ولی داخل توضیحات پلاگین
به جای لینک
https://github.com/maleknejad/obsidian-persian-calendar/

اشتباها به این آدرس لینک داده شده
https://github.com/maleknejad/obisidan-persian-calendar/

**Comment by maleknejad** [comment]
ممنونم آقای هاشمیان عزیز از دقت نظرتون.
